### ISSUE TITLE
Remove remote font loading from default theme

### ISSUE THREAD

**Issue by hadim** [hakimel/reveal.js#1052]
Presentation should be able to run in a totally offline environment and in the default theme the first line imply to load a remote font from google apis.com:

```css
@import url(https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic);
```

So the browser try to use network and a delay happen because it's offline.

I used to add a lato.css file as a first css import in index.html : 

```css
@font-face {
  font-family: 'Lato';
  font-style: normal;
  font-weight: 400;
  src: local('Lato Regular'), local('Lato-Regular'), url(lato-regular.woff) format('woff');
}
@font-face {
  font-family: 'Lato';
  font-style: normal;
  font-weight: 700;
  src: local('Lato Bold'), local('Lato-Bold'), url(lato-bold.woff) format('woff');
}
@font-face {
  font-family: 'Lato';
  font-style: italic;
  font-weight: 400;
  src: local('Lato Italic'), local('Lato-Italic'), url(lato-italic.woff) format('woff');
}
@font-face {
  font-family: 'Lato';
  font-style: italic;
  font-weight: 700;
  src: local('Lato Bold Italic'), local('Lato-BoldItalic'), url(lato-bold-italic.woff) format('woff');
}
```

But it's not enough to avoid the network call. To remove it I had to comment the first line of `css/theme/default.css`.

I guess you can't include lato fonts for license purpose. In this case can't you try to detect if lato fonts have already been loaded and don't make a network call if it does ?

Thank you
