### ISSUE TITLE
'pdf.css' setting to enable slide numbers does not work

### ISSUE THREAD

**Issue by KurtPfeifle** [hakimel/reveal.js#1072]
My *'js/reveal.js'* has the following setting:

```javascript
       // Display the page number of the current slide
       //slideNumber: false,
       slideNumber: true,
```

So slide numbers ***DO*** appear in the slide deck. Here is a screenshot montage showing this (skipping the title slide). The slide numbers are rather small, but they do show up:

![revealjs-slides-html](https://cloud.githubusercontent.com/assets/4747960/5363881/b727674c-7fdf-11e4-9d4b-8566898427d8.png)

My *'css/print/pdf.css'* file has the following setting:

```css
/* SECTION 2: Remove any elements not needed in print.
   This would include navigation, ads, sidebars, etc. */
.nestedarrow,
.reveal .controls,
.reveal .progress,
//.reveal .slide-number,
.reveal .playback,
.reveal .overview,
.fork-reveal,
.share-reveal,
.state-background {
   display: none !important;
}
```

I commented out the line which marks the `.slide-number` as an element that shouldn't be printed.

However, when creating a PDF (using Chrome 39.0.2171.71 (64-bit) on Mac OSX Mavericks 10.9.5), a slide number does only appear for the first slide, not for the following slides. Here is a screenshot montage of the PDF pages (skipping the second slide):

![pdfstylesheet-kungfooforreveal js co---outcome](https://cloud.githubusercontent.com/assets/4747960/5363946/2e008498-7fe0-11e4-998a-dda1470fd84d.png)

The title slide shows navigation controls as well as slide number '0' (very small though, but it is there...). The other slides do show neither navigation controls, nor slide numbers.

I've tried various other methods:

1. Remove the commented out line `//.reveal.js .slide-number,` altogether from the *'pdf.css'*
1. Remove the *complete* SECTION 2 from the *'pdf.css'*
1. Replace the `display: none !important;` statement by a `display: initial !important;` statement.
1. Replace the `display: none !important;` statement by a `display: inline !important;` statement.

Neither did make a difference.

----

My reveal.js is pulled directly from the current GitHub sources (AFAICS it is the very current one); my remote branch when pulling seems to be `origin/dev`.

----

## Update

I tried the same with Firefox (v. 34.0.5) now instead of Chrome, also using a *'....html?print-pdf#/'* URL. Firefox's PDF does look a tad bit different to Chrome's: here we get identical navigation controls plus the slide number '0' on ***ALL*** slides but the title slide (which ***should*** be numbered '0', according to the real HTML slide deck). 

![firefox-pdfstylesheet-kungfooforreveal js co---outcome](https://cloud.githubusercontent.com/assets/4747960/5364615/4a35ef4a-7fe5-11e4-813b-82cdfdab10d5.png)
