### ISSUE TITLE
Former slide is not always cleared from canvas using Firefox

### ISSUE THREAD

**Issue by reagle** [hakimel/reveal.js#1101]
Using Firefox 34.0+build2-0ubuntu0.14.04.1 and reveal3.js from github.
![revealjs-bug](https://cloud.githubusercontent.com/assets/596814/5742446/2b0fd060-9be0-11e4-9c37-1562d9db02a5.png)

**Comment by reagle** [comment]
Actually, I don't think this is a reveal3.js thing. My version prior to 3.0.0 does it too.

**Comment by eKoeS** [comment]
I noticed the same thing while preparing my presentation. After a few attempts, I managed to fix this with the following CSS code:

```css
.reveal section.past,
.reveal section.future {
  overflow: hidden;
}

.reveal section.stack.past,
.reveal section.stack.future {
  overflow: visible;
}

.reveal section.stack.past section,
.reveal section.stack.future section {
  overflow: hidden;
}
```

Bear in mind that I only tested it on my presentation, so it might well break stuff that I haven't used.
