### ISSUE TITLE
Is there a way to use fragments nested ?

### ISSUE THREAD

**Issue by giwrgosdi** [hakimel/reveal.js#1233]
so i have a ul-li in a slide and i want to focus on a single li each time. So in order to focus on the first li (focus visually, for the audience) i use the class "fragment grow".. till now its all fine, but i also want to "grow" each li individually. so when i grow the second li i will "normalize" the first one.

so i looked into the css code of reveal and i made the "fragment normal" class so it can scale back to its normal size. the thing is the i tried to do it like this : 
-li class="fragment grow"- -span class="fragment normal"- First -/span- -/li-

so when i do it like this, it doesn't scale back and it remains in grow state.

any suggestions on how to do it ?
(replace the "-" with ">" and "<")

**Comment by hakimel** [comment]
The "current-visible" fragment style does this but for visibility. Below is modified version of it you can add to your reveal.scss, then use "fragment current-grow".

```scss
.reveal .slides section .fragment.current-grow {
	opacity: 1;
	visibility: visible;

	&.current-fragment {
		transform: scale( 1.3 );
	}
}
```
