### ISSUE TITLE
Show maximum slide size

### ISSUE THREAD

**Issue by jdahm** [hakimel/reveal.js#1554]
Not so much a bug as a feature question. I've looked everywhere for a method to mark the slide boundary so I can tell when a slide has enough content. Has anyone done this?

I've tried this in CSS
```css
.reveal section { border: 5px solid black; min-height: 100%; }
```
but it still conforms to the content on the slide and doesn't maximize the border.

**Comment by jdahm** [comment]
Figured it out. The slides seem to be dynamic given the size of the browser, so I needed to specify it. For example:
```css
.reveal .slides {
	border: 5px solid black;
	min-height: 100%;
	width: 128mm;
	height: 96mm;
}
```
