### ISSUE TITLE
[Workaround] White background when printing pdf

### ISSUE THREAD

**Issue by ebonet** [hakimel/reveal.js#1686]
I was trying to print a pdf from my presentation using the moon theme, but it always printed a white background instead of the background color itself, even though chrome showed the background with correct colors. 

I figured the problem was with the css: the bg color was applied to the body, but never to the .slide-background class (it was transparent). My work around was to add the following piece of code to my custom css. A better solution is to add it on the scss itself.

``` css
@media print {
    .slide-background {
        background-color: #002b36 !important;
        -webkit-print-color-adjust: exact; 
    }
}
```

Hope it helps someone
