### ISSUE TITLE
Vertically fill screen 100%?

### ISSUE THREAD

**Issue by kapelskic** [hakimel/reveal.js#180]
I have been playing with the CSS for this for days upon days now and have yet to be able to get the slides to fill the screen vertically.  I tried adding a #reveal and .reveal in the css and sizing that, didn't work.  I tried adding attributes to .reval .slides, couldn't get that to work.  

Has anyone been able to fill the vertical screen size 100%?

**Comment by lla4um** [comment]
I think this has something to do with all the *.css files. for example. there is a reset_revel.css that coms in ad replaces values. Still can't find the correct values so slideshow resizes based on screen resolution and I can't get rid of that horrid border.

**Comment by vsivsi** [comment]
I too just blew a couple of hours trying to get slide titles and images near the top of the slide...
All of the solutions above were causing the "over the top" symptom that others have reported.
Then I noticed that my slides looked okay if I shrink my browser window down pretty small...

The cause of my "too far from the top" issue turned out to be a combination of:
+ I use a large 30" monitor: 2560x1600
+ I had my slides set for a "native resolution" of 800x600 (crappy projector rez; although the default is 960x700, so not much more)
+ The default value for `maxScale` is 1.5.

So if my browser window was nearly full screen, I was exceeding the `maxScale`, the slide wasn't being scaled up any more, and the "extra space" was going to the top of the slide, not the bottom as I would have expected.

Solution:  `maxScale: 10.0` 

There's 3 hours I'll never get back.  Hope this saves you at least 2.

**Comment by rofrol** [comment]
This works for me:

```javascript
Reveal.initialize({
  center: false
});
```

```css
.reveal .slides > section.present, .reveal .slides > section > section.present {
  min-height: 100% !important;
  display: flex !important;
  flex-direction: column !important;
  justify-content: center !important;
  position: absolute !important;
  top: 0 !important;
}
section > h1 {
  position: absolute !important;
  top: 0 !important;
  margin-left: auto !important;
  margin-right: auto !important;
  left: 0 !important;
  right: 0 !important;
}
```

**Comment by rofrol** [comment]
CSS is enough:

```css
.reveal.slide .slides > section, .reveal.slide .slides > section > section {
  min-height: 100% !important;
  display: flex !important;
  flex-direction: column !important;
  justify-content: center !important;
  position: absolute !important;
  top: 0 !important;
  align-items: center !important;
}
section > h1, section > h2 {
  position: absolute !important;
  top: 0 !important;
  margin-left: auto !important;
  margin-right: auto !important;
  left: 0 !important;
  right: 0 !important;
  text-align: center !important;
}
.print-pdf .reveal.slide .slides > section, .print-pdf .reveal.slide .slides > section > section {
  min-height: 770px !important;
  position: relative !important;
}
```

http://stackoverflow.com/questions/23241903/positionfixed-in-reveal-js/34922750#34922750
