### ISSUE TITLE
Left align slide text

### ISSUE THREAD

**Issue by afredstonhermann** [hakimel/reveal.js#1897]
I'm creating a presentation in rmarkdown with reveal.js and would like the text on my slides to be left-aligned, not centered. I understand there is a global option to toggle `center` on/off, but this only affects vertical centering when I knit the HTML file. How do I left-align text for the entire file? The output options I am using are: 
```
output:
  revealjs::revealjs_presentation:
    theme: night
    transition: none
    center: false
    reveal_options:
      slideNumber: true
      progress: true
  beamer_presentation:
    toc: false
    incremental: true
```

Thanks for the help and for creating such a useful tool!
