### ISSUE TITLE
Custom element position with CSS

### ISSUE THREAD

**Issue by troncomputers** [hakimel/reveal.js#1995]
Hi!
Is it possible to use custom CSS like
```css
p { position:absolute;bottom:10px }
```
for
```html
<section data-background-image="img/kasiarz_logowanie.png" data-background-size="85%" data-markdown>
<p style="position:absolute;bottom:10px">Siema</p>
</section>
```
It's not working
