### ISSUE TITLE
align-content (of grid layout) property interferes with the max-height and max-width properties?

### ISSUE THREAD

**Issue by allsey87** [hakimel/reveal.js#2003]
I am trying to layout my slides using a div with `display: grid` mode. Everything is working really well, however, when I try to use the `align-content: center` property to vertically align content inside the grid my images and videos height and width attributes seem to be overridden and set to 0pt x 0pt.

From using the Google Chrome DevTools, it seems that this might have to do with the `max-height` and `max-width` properties coming from the theme (in this case, white.css):

```css
/* Ensure certain elements are never larger than the slide itself */
.reveal img,
.reveal video,
.reveal iframe {
  max-width: 95%;
  max-height: 95%; }
```
By disabling these attributes my images and videos reappear with non-zero dimensions, however, they are distorted and larger than the slide itself. https://github.com/allsey87/presentations/tree/defence is my repository where I am working with a extended version of Reveal.js and https://github.com/allsey87/presentations/commit/c02784d9cbf076d9580f8201be4ca608f7c2b54a is the commit where I have introduced the two offending properties, which I have commented out for the moment.
