### ISSUE TITLE
Nested List with Count

### ISSUE THREAD

**Issue by vandalvnl** [hakimel/reveal.js#2060]
Hello, 

I loved your project and using enough. I noticed there are no numbered lists with subtopics, so theres my contribution:

```css
.reveal .ol {
	counter-reset: item;
	list-style-type: decimal;
}

.reveal .li {
	display: block;
}

.reveal .li:before {
	content: counters(item, ".") ". ";
	counter-increment: item;
}
```
