### ISSUE TITLE
Background transition: Overwriting with 'fade' doesn't work

### ISSUE THREAD

**Issue by Aisbergg** [hakimel/reveal.js#2066]
Applying `data-background-transition="fade"` on a slide doesn't work. It seems that the *fade* transition is simply not defined in the `css/reveal.scss`.

**Comment by jmona789** [comment]
Are you sure it should `data-background-transition` and not `data-transition`.  They are both listed in the docs, and `data-background-transition` seems to only be for slides using a iframe background

**Comment by Aisbergg** [comment]
There are two different kind of transitions, one for the content and one for the background. I want to address the transition of the background. As the [documentation on background transitions](https://github.com/hakimel/reveal.js#background-transitions) says, the default transition effect for backgrounds can be change. So I set `backgroundTransition: 'convex'` in my `Reveal.initialize()` and now I want to override the effect on a specific slide. Looking into the [SCSS](https://github.com/hakimel/reveal.js/blob/a0c013606e130baad976195730dcd7e7cd9e2855/css/reveal.scss#L1126) I see the transitions `none`, `slide`, `convex`, `concave`, `zoom` but `fade` is missing. Therefore I cannot apply `data-background-transition="fade"` on a slide to override my default transition.

A fix could be something like this:

```css
/* Fade */
.reveal[data-background-transition=fade] > .backgrounds .slide-background,
.reveal > .backgrounds .slide-background[data-background-transition=fade] {
  transform: none;
  transition: opacity 0.5s;
}
```

but I am not sure if it is enough or if additional css selectors need to be applied like those for the `convex` effect.
