### ISSUE TITLE
I WANT TOP ALIGN

### ISSUE THREAD

**Issue by G1305** [hakimel/reveal.js#2099]
`<section data-vertical-align-top>
				I WANT TOP ALIGN
			</section>`
TOP align don't affects, how to fix?
![screenshot 6](https://user-images.githubusercontent.com/34474564/36312818-23084abc-1349-11e8-87e6-2fddc687359a.png)

**Comment by bnjmnt4n** [comment]
Seems like you saw #1608, but since that hasn't been merged that syntax is not available in Reveal yet. You have to specify the CSS yourself:

```css

/* Slide-specific vertical centering override */
.reveal .slides section[data-vertical-align-top]{
	top: 0 !important;
}
```
