### ISSUE TITLE
Grow and shrink fragment styles not working on span within P

### ISSUE THREAD

**Issue by reagle** [hakimel/reveal.js#2126]
As discussed on [pandoc-discuss](https://groups.google.com/d/msg/pandoc-discuss/MtKe52maiGE/uGSIYMQDBwAJ), pandoc will generate HTML from this in which grow and shrink do not work.

https://reagle.org/joseph/talks/2014/exemplar.html#/fragment-styles-new

```
## Fragment styles new

::: {.incremental}

[current-visible]{.fragment .current-visible}

[highlight-red]{.fragment .highlight-red}

[highlight-green]{.fragment .highlight-green}

[highlight-blue]{.fragment .highlight-blue}

[fade-out]{.fragment .fade-out}

[grow]{.fragment .grow} <!-- https://github.com/hakimel/reveal.js/issues/2126 -->

[shrink]{.fragment .shrink} <!-- https://github.com/hakimel/reveal.js/issues/2126 -->

:::
```

**Comment by lunchboxer** [comment]
see this [stackoverflow answer](https://stackoverflow.com/questions/24961795/how-can-i-use-css3-transform-on-a-span)

The problem is that the html span element is not subject to transform. You can fix this by changing the display property in your css.

```css
.reveal .slides section span.fragment.grow.visible {
  display: inline-block;
  -webkit-transform: scale(1.3);
  transform: scale(1.3);
}
```

That will probably give you some unwanted side-effects, like not properly spacing between your span and the text around it. If your span is really an inline element like a word in a paragraph, you would do better just to change the grow effect into something more suitable for text

```css
.reveal .slides section span.fragment.grow.visible {
  font-weight: bold;
  font-size: 130%;
  -webkit-transform: none;
  transform: none;
}
```

The same applies to shrink
