### ISSUE TITLE
Image sizing woes

### ISSUE THREAD

**Issue by Jmuccigr** [hakimel/reveal.js#2127]
I'm using pandoc to convert markdown to reveal.js, and I'm trying to maximize image size and running into some problems. What I see is that a large image will not be resized and so it runs off the screen to the bottom. I'm trying to prevent this and I don't quite understand what's keeping the image from being confined to the height of the display.

Using Safari's developer tools, I can see that the div#slides gets the smaller height of the display, as do the enclosing items (like body), but then the enclosed section with class "slide level6 present" gets the larger height (of the window?), which puts the enclosed image off the screen.

I suspect there's some CSS thing I don't understand here. If I force the section to inherit its height, that helps, though I still have to explicitly size the elements it encloses. Below is the starting text of a short slideshow, up to the included scripts and then reveal.initialize.

(I also see the various scaling options in reveal.initialize, but I get large images going off the bottom even playing with these.)

TIA.

```
<body>
  <div class="reveal">
    <div class="slides">

<section id="title-slide">
  <h1 class="title">Title</h1>
  <p class="author">John Doe</p>
  <p class="date">15 March</p>
</section>

<section class="slide level6">

<p>Some text</p>
<figure>
<img data-src="/path/to/image.jpg" alt="Caption" /><figcaption>Caption</figcaption>
</figure>
</section>
<section class="slide level6">

<figure>
<img data-src="/path/to/image.jpg" alt="Caption" /><figcaption>Caption</figcaption>
</figure>
</section>
    </div>
  </div>
```

**Comment by Jmuccigr** [comment]
I'll put up a link to my css when I get it done, but here's how I managed to get full-sized, proportional images via css. The captions are hidden unless hovered over and cover the bottom portion of the slide. Still need to tweak them a bit, but I'm fairly happy with this so far.
```css
.reveal figure img {
  box-shadow: none;
  max-width: 100%;
  object-fit: contain;
}

.reveal figcaption {
  position: absolute;
  margin: auto;
  width: 100%;
  left: 0;
  text-align: center;
  bottom: 1em;
  height: auto;
  display: block;
  background-color: white;
  color: black;
  font-size: small;
  opacity: 0;
}

.reveal figcaption:hover {
  opacity: .9;
}
```
