### ISSUE TITLE
Fix for selected present and hover slides in overview mode

### ISSUE THREAD

**Issue by gw0** [hakimel/reveal.js#2296]
In overview mode in `white.css` it is a bit unclear what is the selected slide. To improve on this, first the outline color should be made darker. Then the first slide in a stack of slides should not have a selected outline if it is not directly selected.

```css
.reveal.overview .slides section:hover,
.reveal.overview .slides section.present { outline: 10px solid #999999; }
.reveal.overview .slides section.stack:hover,
.reveal.overview .slides section.stack.present { outline: initial; outline-offset: initial; }
```
