### ISSUE TITLE
Variable text at bottom of slide

### ISSUE THREAD

**Issue by harveyslash** [hakimel/reveal.js#2404]
I want to have attribution/notes at the bottom of the screen, which will be used for attribution mainly. 

The main things im looking for are: 
small size, 
horizontal center 

and exact same positioning vertically. 

Looking around, I've found this css:
```

.reveal.slide .slides > section, .reveal.slide .slides > section > section {
    min-height: 100% !important;
    display: flex !important;
    flex-direction: column !important;
    justify-content: center !important;
    position: absolute !important;
    top: 0 !important;
    align-items: center !important;
}
section > h1, section > h2 {
    position: absolute !important;
    top: 0 !important;
    margin-left: auto !important;
    margin-right: auto !important;
    left: 0 !important;
    right: 0 !important;
    text-align: center !important;
}
.print-pdf .reveal.slide .slides > section, .print-pdf .reveal.slide .slides > section > section {
    min-height: 770px !important;
    position: relative !important;
}

.reveal[data-background-transition=fade] > .backgrounds .slide-background,
.reveal > .backgrounds .slide-background[data-background-transition=fade] {
    transform: none;
    transition: opacity 0.5s;
}



.attribution {
    position: absolute;
    /*padding-top: 80vh !important;*/
    bottom: 10%;
    left: auto;
    font-size: 0.25em !important;
}

```

Where the attribution class is being used like this:

           ``` <span class="attribution" data-fragment-index="0">Press  ➡️ (again)</span>```

This works perfectly when I have transition set to 'slide', but when I change it to anything other than slide, the bottom text goes towards the middle of the screen. 

Any way to fix this problem?

**Comment by JOduMonT** [comment]
I was looking for this behavior too and I made it happen with a mix of your code and [his code](https://github.com/hakimel/reveal.js/issues/180#issuecomment-173543708)
I simply removed: `justify-content: center !important;` than add your __.attribution__ part

````css
.reveal .slides > section.present, .reveal .slides > section > section.present {
  min-height: 100% !important;
  display: flex !important;
  flex-direction: column !important;
  position: absolute !important;
  top: 0 !important;
}
section > h1 {
  position: absolute !important;
  top: 0 !important;
  margin-left: auto !important;
  margin-right: auto !important;
  left: 0 !important;
  right: 0 !important;
}

.print-pdf .reveal .slides > section.present, .print-pdf .reveal .slides > section > section.present {
  min-height: 770px !important;
  position: relative !important;
}

.attribution {
  position: absolute;
  bottom: 0;
  left: 0;
} 
````

note in my __Reveal.initialize__ part; `center: false,`
