### ISSUE TITLE
Full width possible, but not full height

### ISSUE THREAD

**Issue by TcaManager** [hakimel/reveal.js#2522]
Hi,
I tried those plugins, but found no way to reach a full screen slide. Is there a way to suppress all the white spaces around the <section> tag?
https://github.com/mkordulewski/reveal.js-fullscreen-code
https://rajgoel.github.io/reveal.js-demos/fullscreen-demo.html

Is there a way I can get this code to render fullscreen, with a blue column on the left, a grey column on the right, no white space but 5px margin, and being resizeable?
```css
/*********************************************
 * Columns
 *********************************************/
.container{
    display: flex;
    min-height: 500px;
}
.fake-margin{
    flex: 1;
    margin: 5px;
}

.fake-content{
    flex: 4;
    margin: 5px;
}

.grey-content{
  background: #e5e5e5;
}

.blue-content{
  background: #00598d;
}
```

```html
<section>
  <div class="container">
    <div class="fake-margin blue-content">
    </div>
    <div class="fake-content grey-content">
      <h1>Reveal.js</h1>
      <h3>The HTML Presentation Framework</h3>
      <p>
         <small>Created by <a href="http://hakim.se">Hakim El Hattab</a> and <a href="https://github.com/hakimel/reveal.js/graphs/contributors">contributors</a></small>
      </p>
    </div>
  </div>
</section>
```
