### ISSUE TITLE
Slide effects missing when adding bootstrap 4

### ISSUE THREAD

**Issue by DMW007** [hakimel/reveal.js#2607]
I want to use Bootstrap, mainly for the flexbox and grid layout. So I used the latest stable release from reveal.js and bootstrap (v4.4.1) like this:

```bash
wget https://github.com/hakimel/reveal.js/archive/3.9.2.zip
unzip 3.9.2.zip
cd reveal.js-3.9.2
npm install
npm i -D bootstrap
```

Now, in `index.html`, I added
```html
<link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap.min.css">
```
before 

```html
<link rel="stylesheet" href="css/reset.css">
```
to make sure that reveal.js can override possible conflicts from bootstrap. This seems to generally work (also the flexbox layout). But since bootstrap is added, the slide effect when navigating between slides is gone: Instead of a smooth slide effect, it's a hard change. This only appears when bootstrap is added, removing bootstrap brings back the smooth slide effects. 

Is there a way to get those smooth slides back when using together with Bootstrap? I think reveal.js with Bootstrap is a strong bundle, since a lot of people are familar with Bootstrap, which could re-use this knowledge for making reveal.js presentations.

**Comment by mauricesnip** [comment]
Encountered the same issue using Bootstrap 4.5. The following CSS in reboot.(s)css causes the issue:

```css
// Always hide an element with the `hidden` HTML attribute (from PureCSS).
// Needed for proper display in IE 10-.
[hidden] {
  display: none !important;
}
```

In Reveal.js, slides get the `hidden` attribute when they're not visible. Though, by adding the above CSS, slides stay hidden until the `hidden` attribute is removed. Inline styles like `display: block;` won't overrule that by specificity. This makes the 'transition' instant (from `display: none;` to `display: block;`) Now, normalize.css handles this by not adding `!important` to the equation. And it makes me wonder if `!important` is really necessary here.

The question is; should this be taken care of in Reveal.js or Bootstrap?

@hakimel Your opinion on this?

**Comment by alshar** [comment]
@mauricesnip 

```css
.reveal [hidden] {
    display: block !important;
}
```
in my css worked for me thank you!
