### ISSUE TITLE
Tweaking layout of contents to respect header/footer

### ISSUE THREAD

**Issue by cifkao** [hakimel/reveal.js#2707]
I would like to know whether it is possible to specify the bounding box of the slide's contents. Right now it seems that it cannot be done easily.

My use case is that I have added a custom (fixed-height) footer to my presentation, and I want to make sure that the content layout respects the footer. That is:
- The content should be centered in the area above the footer, and not on the whole slide.
- Using `.r-stretch` should not make the content run over the footer.

It would be great if it were possible to set the slide's inner dimensions explicitly, e.g. by specifying the top, left, bottom and right margin in pixels. Perhaps the `margin` property can be extended to allow specifying an object, e.g. `{bottom: 100, top: ...}`.

Ideally, it should be possible to specify different margins for different slides, as not all slides may have a footer.

**Comment by cifkao** [comment]
A workaround for the footer issue is to add a filler (pseudo-)element of the same height as the footer at the bottom of every slide, e.g.:
```scss
$footerHeight: 60px;

.reveal .slides > footer {
  width: 100%;
  height: $footerHeight;
  position: absolute;
  bottom: 0;
}

/* Spacer to prevent the content from running into the footer. */
.reveal .slides > section::after {
  content: '';
  display: block;
  height: $footerHeight;
}
```
