### ISSUE TITLE
Allow custom fragment transitions

### ISSUE THREAD

**Issue by pykong** [hakimel/reveal.js#2927]
I want to be able to define my own fragment transitions using CSS.
Does the current version of reveal.js already support such?

I believe it would be very very easy to implement this feature. All it would take would be to define a transition that does not apply an effect itself. 

Right now I am using the `highlight-current-color` as a workaround by overriding their applied CSS style rules:

For example:

```css
.current-fragment.highlight-current-red {
  transform: rotate(45deg);  /* my custom effect */
  color: black !important; /* suppress highlight-current-red style*/
}
```

Of course, to make it more sophisticated, it would be desirable to specify whether the effect should persist after the fragment is no longer the current one.

See: https://revealjs.com/fragments/
