### ISSUE TITLE
Question: Publishing with plugins to RStudio Connect?

### ISSUE THREAD

**Issue by AMNakamura** [hakimel/reveal.js#2930]
Good morning. I've developed presentations using this package (version 0.9) without issues in RStudio IDE (version 1.4.1103.4, Platform: x86_64-redhat-linux-gnu (64-bit), R version 3.6.0), but I can't seem to publish to RStudio Connect if my code includes the reveal.js plugins.

This is the error returned:

```
Error in (function (incremental = FALSE, center = FALSE, slide_level = 2, :
04/03 14:25:02.921 (GMT)
Using reveal_plugins requires self_contained: false
04/03 14:25:02.921 (GMT)
Calls: local ... <Anonymous> -> create_output_format -> do.call -> <Anonymous>
```

Values for incremental and self-contained are set to TRUE and FALSE, respectively in my YAML, so the error isn't making sense to me. It seems I have two options for publishing successfully:

1. With plug-ins, but without the source code
2. With source code, but without plug-ins

I've included a simple example of the source code (just the YAML and two placeholder slides), below.

```
---
title: "My Title"
author: "Author Name"
date:  "`r Sys.Date()`"
output:
  revealjs::revealjs_presentation:
    incremental: true
    self_contained: false
    reveal_plugins: ["notes", "chalkboard", "menu"]
link-citations: yes
---

## Slide 1

- Bullet 1
- Bullet 2
```

I really like revealjs. Any help is much appreciated.
