### ISSUE TITLE
Python style missing coloring functions

### ISSUE THREAD

**Issue by mzahran001** [hakimel/reveal.js#3490]
Hi
Thank you for the fantastic project

I wanted to change the style of the code from 
![image](https://github.com/hakimel/reveal.js/assets/15180702/2f4e3960-e7e7-494e-a40c-016634b76d03)
to
![image](https://github.com/hakimel/reveal.js/assets/15180702/08c31b73-28df-46ed-b188-7f0f1f3656a8)

But every time I try, it fails. I guess I am missing something in the code.

How I tried to do it?
- By changing the monokai.css with a custom.css 
```css
/* Setting up the general background and text color */
.hljs {
  display: block;
  overflow-x: auto;
  padding: 0.5em;
  background: #282a36;
  /* Background from the image */
  color: #ffffff;
  /* General Text Color */
}

/* Keywords like from, import */
.hljs-keyword {
  color: #8be9fd;
  /* Light Cyan */
}

/* Functions/Methods like Sequential, Dense, Adam */
.hljs-title,
.hljs-name {
  color: #50fa7b;
  /* Green */
}

/* Strings 'tanh' */
.hljs-string {
  color: #f1fa8c;
  /* Yellow */
}

/* Parameters and properties like learning_rate */
.hljs-params,
.hljs-attr {
  color: #f1fa8c;
  /* Yellowish */
}

/* Numbers like 0.05 */
.hljs-number {
  color: #bd93f9;
  /* Purple */
}

/* Comments */
.hljs-comment {
  color: #6272a4;
}

/* Other categories from the original CSS */
.hljs-tag,
.hljs-selector-tag,
.hljs-literal,
.hljs-strong {
  color: #f92672;
}

.hljs-code {
  color: #66d9ef;
}

.hljs-attribute,
.hljs-symbol,
.hljs-regexp,
.hljs-link {
  color: #bf79db;
}

.hljs-bullet,
.hljs-subst,
.hljs-section,
.hljs-emphasis,
.hljs-type,
.hljs-built_in,
.hljs-builtin-name,
.hljs-selector-attr,
.hljs-selector-pseudo,
.hljs-addition,
.hljs-variable,
.hljs-template-tag,
.hljs-template-variable {
  color: #a6e22e;
}

.hljs-quote,
.hljs-deletion,
.hljs-meta {
  color: #75715e;
}

/* Bold categories */
.hljs-keyword,
.hljs-selector-tag,
.hljs-literal,
.hljs-doctag,
.hljs-section,
.hljs-type,
.hljs-selector-id {
  font-weight: bold;
}
```
