### ISSUE TITLE
What is the theme used in https://revealjs.com/demo?

### ISSUE THREAD

**Issue by Kabouik** [hakimel/reveal.js#3493]
The theme used on https://revealjs.com/demo does not seem to be the same as that in the `demo.html` in the repository, and I can't find any `theme` line when looking at the HTML code of this demo. It seems to link to a main.css directly on https://reveal.com. 

The theme does look pretty similar to `dracula.css`, but there are differences. I'd be interested in using the exact same as in the online demo.

**Comment by t-fritsch** [comment]
hello, the theme used on the doc website is a variation of the default 'Black' theme. The customizations made are in the revealjs.com website repository , in the `decks.scss` file : 

https://github.com/reveal/revealjs.com/blob/f4a4db97ab6450377ffe7fb8cec7c51cbe5116eb/css/decks.scss#L31-L57 

```scss
.reveal {
    font-size: 36px;
    background-color: darken(desaturate(#2d234c, 10%),10%);
}

.reveal a,
.reveal .controls button,
.reveal .progress span {
    @apply text-pink-500;
}

.reveal .progress {
    height: 6px;
}

.reveal h1, h2, h3, h4, p, ul {
    font-family: 'Inter', sans-serif !important;
}

.reveal iframe {
    margin-left: auto;
    margin-right: auto;
}

.reveal img {
    display: inline-block;
}
```

note that for color codes, the website uses tailwind variables and scss functions, the resulting colors are : 
- background : `#1a1626`
- links / controls / progress : `#d85c99`
