### ISSUE TITLE
@media print and <!-- .element: style="font-size: 60%" -->

### ISSUE THREAD

**Issue by jpggithub** [hakimel/reveal.js#3556]
When printing a presentation, a directive like `<!-- .element: style="font-size: 60%" -->`  for  a paragraph is not respected.
(reveal.js v5.0.3)

In `/css/print/paper.scss`, the following rule causes the problem:

```css
@media print {
[...]font-size: 20pt!important;
	html:not(.print-pdf) .reveal {
[...]
		p, td, li {
			font-size: 20pt!important;
[...]
		}
```

It would be more obvious to have something like `font-size: 20pt!important;`, no?

Without the `!important` part, it could be possible to configure the print version as wished.
With  `!important` part, it can't be as far as I understand.
