### ISSUE TITLE
Documentation issue: definition of "fade-in-then-out" and "current-visible"

### ISSUE THREAD

**Issue by keul** [hakimel/reveal.js#3572]
On https://revealjs.com/fragments/ both `fade-in-then-out` and `current-visible` are defined as "Fades in, then out on the next step"

**Comment by NicolasCwy** [comment]
I used them both and it seems to reflect the behaviour of the effects, although I'm unsure why they are duplicated.

**Comment by ssokolow** [comment]
I can confirm that. There's a single definition of each in the SCSS source, and it looks like this:

```scss
.reveal .fragment.fade-in-then-out,
.reveal .fragment.current-visible {
	opacity: 0;
	visibility: hidden;

	&.current-fragment {
		opacity: 1;
		visibility: inherit;
	}
}
```

The only other mention of them in un-compiled/un-minified files is this line from `js/utils/constants.js`:

```
export const FRAGMENT_STYLE_REGEX = /fade-(down|up|right|left|out|in-then-out|in-then-semi-out)|semi-fade-out|current-visible|shrink|grow/;
```
