### ISSUE TITLE
The text of <li class="fragment"> temporarily loses its CSS style

### ISSUE THREAD

**Issue by ChoCho66** [hakimel/reveal.js#3624]
As title, when `<li class="fragment">` becomes `<li class="fragment visible current-fragment">`, the text of `<li class="fragment">` temporarily loses its CSS style.

Below is a video of this situation.

https://github.com/hakimel/reveal.js/assets/72805700/98966cd0-ba8a-4c18-bec9-b6edbe732728

I use `quarto` to generate `revealjs`

A small sample of `qmd` is
```qmd
---
title: "Test"
format: revealjs
incremental: true
css: "custom.css"
---

## Test

- Α
  - a
  - b
    - β
  - c
```

and my `custom.css` file is
```css
.fragment {
  opacity: 1 !important;
  visibility: visible !important;
  filter: brightness(0.01) invert(0.8) !important;
}
.fragment.visible {
  filter: none !important;
}
.reveal {
  color: blue;
}
```

Is there any good way to solve it?
