### ISSUE TITLE
Transform and data auto animate do not work together.

### ISSUE THREAD

**Issue by boomsi** [hakimel/reveal.js#3652]
You can see here [codesendbox](https://codesandbox.io/p/devbox/reveal-js-852h22?file=%2Findex.html%3A30%2C33)

When i set child`transform: rotate(20deg);`. When the animation ends, the rotation does not take effect.

So how to set child `transform` attr if i need animate?

**Comment by keflavich** [comment]
Same question - how can one animate rotation?

**Comment by keflavich** [comment]
I was able to get rotated animation working with fragments, circumventing `data-auto-animate`:
```css
.fragment.rotated {
    rotate:var(--rotation);
    visibility: hidden;
    opacity: 0;
    /* 'important' overrides data-auto-animate */
    transition: rotate var(--transition-duration, 1s) ease-in-out !important;

    &.visible.current-fragment {
        visibility: visible;
        opacity: 1;
        rotate:var(--rotation);
        transition: rotate var(--transition-duration, 1s) ease-in-out !important;
    }

    &.visible {
        rotate:0deg;
        transition: rotate var(--transition-duration, 1s) ease-in-out !important;
    }
}
```

```html
        <img src="image.png" style="position: absolute;  top:5%; left:10%; --rotation:-45deg; transform-origin: 0px 0px; --transition-duration: 0.5s;" class="fragment rotated">
        <div class=fragment placeholder-for-fadeout-animation></div>
```
This works by fading in the element, then having the 'fade-out' perform a rotation.  The placeholder is a blank so that there is one more fragment to build such that the rotated fragment is visible but not current.

(the `transform-origin: 0px 0px` is needed to specifically place the image in the frame, which was important for my use case)
