### ISSUE TITLE
nested lists are unstyled

### ISSUE THREAD

**Issue by paulirish** [hakimel/reveal.js#47]
I went with something like 

``` css
#reveal ol ul {
    display: block;
    margin-left: 80px;

 }
```

but the selector probably needs to capture more than just that ol ul combo
