### ISSUE TITLE
Rendering problems with jumly

### ISSUE THREAD

**Issue by rparree** [hakimel/reveal.js#539]
Hi,

First of all would like to say how awesome this library is. We are looking into this to use for a base for all our courseware (to replace our own old propitiatory system to produce PDF)

I am trying to embed UML diagrams using another awesome library [jumly](https://github.com/tmtk75/jumly/). However the image below shows how the diagram is rendered on a slide:

![image](https://f.cloud.github.com/assets/359605/847755/7c26afc0-f446-11e2-859b-12fd6cc17276.png)

And in a "empty" html page it renders like:

![image](https://f.cloud.github.com/assets/359605/847758/aa0a027a-f446-11e2-8d6e-5ca216957b3a.png)

How should i tackle this one?

Thanks.,

Raphael

**Comment by juankakode** [comment]
@rparree I was able to fix this by adding the same css + some more, 

```css
.reveal .jumly *{
	font-size : 10pt;
	text-align: start;
	color:black;
}

.jumly .diagram {
	margin-left: auto;
	margin-right: auto;
}
```
Then to do a diagram I do

```html
<div class="jumly">
	<script type='text/jumly+sequence'>
		@found "You", ->
	  		@message "get", "JUMLY"
	</script>
</div>
````
