### ISSUE TITLE
Set Background Image for All Slides/Sections

### ISSUE THREAD

**Issue by ghost** [hakimel/reveal.js#566]
I'm using reveal with the markdown plugin. I can't figure out how to use an image as a background for all slides. I have tried the traditional CSS in the theme, but that doesn't work. I can set an image for an individual slide with the data-state method, but I would like to set the image in css and use the same theme for multiple presentations.

**Comment by romain-dartigues** [comment]
Note for future readers (as of version 3.8).

Setting a background to the body element did not play well during printing; I had to add:
```css
@media screen {
	/* this rule does not have to be restricted to "screen" media,
	 * but it appear to make the "print" rendering slightly faster */
	body {
		background:url('path/to/background.jpg');
		background-size:cover;
	}
}

@media print {
	.backgrounds {
		background:url('path/to/background.jpg');
		/* if you use "cover" on screen, you probably want "contains" on print */
		background-size:contain;
	}
}
```
