### ISSUE TITLE
How to add fontawesome

### ISSUE THREAD

**Issue by EpokK** [hakimel/reveal.js#601]
I added `fontawesome.css` to my html page but I can't use fontawesome in my `sections`. Can you help me ?

**Comment by rparree** [comment]
I am using a custom scss like this:

```scss
$fa-font-path: "bower/font-awesome/fonts";
@import "bower/font-awesome/scss/variables";
@import "bower/font-awesome/scss/mixins";
@import "bower/font-awesome/scss/path";
@import "bower/font-awesome/scss/spinning";

.reveal {
  @import "bower/font-awesome/scss/core";
  @import "bower/font-awesome/scss/larger";
  @import "bower/font-awesome/scss/fixed-width";
  @import "bower/font-awesome/scss/list";
  @import "bower/font-awesome/scss/bordered-pulled";
  @import "bower/font-awesome/scss/rotated-flipped";
  @import "bower/font-awesome/scss/stacked";
  @import "bower/font-awesome/scss/icons";
}
```

Some have mixins so these were added outside the `.reveal` parent selector.

This way i can also use lists etc (not only `<i>`)
