### ISSUE TITLE
Reveal overrides html align

### ISSUE THREAD

**Issue by hadley** [hakimel/reveal.js#654]
e.g. if you have a table with `<td align="right">123</td>` it will be aligned left because of:

``` css
.reveal table td {
    text-align: left;
    padding-right: .3em;
}
```
