### ISSUE TITLE
Overriding Firefox 24.0 black background in fullscreen mode

### ISSUE THREAD

**Issue by scottdavis99** [hakimel/reveal.js#668]
I'm not sure if this is a bug or expected behavior in Firefox 24.0, but when you enter fullscreen mode by pressing the "f" key, the background color is set to black. (This makes black text on a black background invisible, although my images still appear.) I've replicated this on both Windows and OS X.

NOTE: this behavior DOESN'T manifest when I click the double-arrow key in the upper right corner on OS X -- only when I press the "f" key.

One workaround is to hardcode the bgcolor attribute on the body element:

``` html
<body bgcolor="white">
```

Another is to use the -moz-full-screen CSS selector with !important to override.

``` css
      body:-moz-full-screen {
        background-color: #fff !important;
      }
```
