### ISSUE TITLE
Replace text on fragment transition

### ISSUE THREAD

**Issue by chrisspiegl** [hakimel/reveal.js#745]
Is there an easy way to replace the content of an `<p>` or `<span>` tag with new text?

The problem currently is that if I do the following, the content is next to each other and it is not replacing but rather just hiding the old content:

```
<span class="fragment fade-out" data-fragment-index="0">1</span>
<span class="fragment fade-in" data-fragment-index="0">x</span>
```

Would be a nice feature to have.

**Comment by blairvanderhoof** [comment]
This doesn't work well if you have a title.  Since i wont know the height of your data, the title will sit in the vertical center and push your content down too much.  Wish there was a way to support replacing fragments.

**Comment by lilaL** [comment]
Hey,
this only worked out fine, but still they are offsets!
```
<div style="position:relative" >
        <p class="fragment fade-in" style="position:absolute; margin-left: auto; margin-right: auto; left: 0; right: 0;" data-fragment-index="0">
        TWO
        </p>
        <p class="fragment fade-out" style="position:absolute; margin-left: auto; margin-right: auto; left: 0; right: 0;" data-fragment-index="0">
          ONE
        </p>
    </div>
```

**Comment by okyear** [comment]
Hi,
There is another way I find more elegant :

Add this style in your css :
```css
.reveal .slides section .fragment.step-fade-in-then-out {
	opacity: 0;
	display: none; }
.reveal .slides section .fragment.step-fade-in-then-out.current-fragment {
	opacity: 1;
	display: inline; }
```

Then, you can use it this way :
```html
<section>
	<section>
		<p class="fragment step-fade-in-then-out">One</p>
		<p class="fragment step-fade-in-then-out">Two</p>
		<p class="fragment step-fade-in-then-out">Three</p>
		<p class="fragment step-fade-in-then-out">Four</p>
	</section>
</section>
```
