### ISSUE TITLE
Vertical centering in print PDF version view

### ISSUE THREAD

**Issue by jtomaszewski** [hakimel/reveal.js#862]
Hey!

It's more like a feature, not a must, but I think it would be useful. Currently, there is no vertical centering in PDF's view of the slides. Propably because it wasn't easy to achieve with CSS.

Today however we can easily use [flexbox](http://philipwalton.github.io/solved-by-flexbox/demos/vertical-centering/) which is well supported by Chrome. Adding just those lines in `css/print/pdf.css` will make every slide aligned vertically to middle, instead to top:

``` css
.reveal .slides section {
  display: flex !important;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}
```

Note: This will change the look of existing slides in print view.
However I wouldn't ignore it - maybe we could include this in the wiki, or with a JS setting like `alignSlidesToMiddleInPrintView: true` ?
